
'use client';

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useBotContext } from "@/context/bot-provider";
import { cn } from "@/lib/utils";

export default function StrategiesContent() {
  const { isBotActive } = useBotContext();
  const strategies: any[] = [];

  return (
      <div className="grid gap-6 md:grid-cols-2">
        {strategies.length > 0 ? strategies.map((strategy) => (
            <Card key={strategy.symbol} className={cn(
                "border-primary/50 shadow-lg shadow-primary/20",
                isBotActive && "animated-grid"
            )}>
                {isBotActive && <div className="scanner-line !bg-gradient-to-r from-transparent via-primary/80 to-transparent" style={{animationDuration: '4s'}}></div>}
                <CardHeader className="relative z-10">
                    <div className="flex items-center justify-between">
                         <CardTitle className="font-headline text-primary">{strategy.symbol}</CardTitle>
                         <Badge variant={strategy.side === 'Buy' ? 'default' : 'destructive'} className={cn(isBotActive && "pulse-glow border-2 border-primary-foreground/50")}>
                            {strategy.side}
                         </Badge>
                    </div>
                    <CardDescription>Strategy generated by the Decider Bot</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4 relative z-10">
                    <div className="flex justify-between items-center">
                        <span className="text-muted-foreground">Entry Price</span>
                        <span className="font-medium font-code">${strategy.entry.toLocaleString()}</span>
                    </div>
                    <div className="flex justify-between items-center">
                        <span className="text-muted-foreground">Stop Loss</span>
                        <span className="font-medium font-code">${strategy.sl.toLocaleString()}</span>
                    </div>
                    <div className="flex justify-between items-center">
                        <span className="text-muted-foreground">Take Profit(s)</span>
                        <div className="flex gap-2">
                            {strategy.tp.map(price => (
                                <Badge key={price} variant="secondary" className="font-code">${price.toLocaleString()}</Badge>
                            ))}
                        </div>
                    </div>
                    <div className="flex justify-between items-center">
                        <span className="text-muted-foreground">Position Size</span>
                        <span className="font-medium font-code">{strategy.size}</span>
                    </div>
                </CardContent>
            </Card>
        )) : (
             <Card className={cn("md:col-span-2 flex items-center justify-center py-20", isBotActive && "animated-grid")}>
                {isBotActive && <div className="scanner-line !bg-gradient-to-r from-transparent via-primary/80 to-transparent"></div>}
                <CardHeader className="relative z-10 text-center">
                  <CardTitle className="font-headline text-primary">Decider</CardTitle>
                  <CardDescription>The Decider bot is waiting for high-confidence signals.</CardDescription>
                </CardHeader>
            </Card>
        )}
      </div>
  );
}
