
'use client';

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { BarChart as BarChartIcon, BrainCircuit, Rss } from "lucide-react";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid } from "recharts";
import { useBotContext } from "@/context/bot-provider";
import { cn } from "@/lib/utils";

const chartConfig = {
    bullish: {
      label: "Bullish",
      color: "hsl(var(--chart-2))",
    },
    bearish: {
      label: "Bearish",
      color: "hsl(var(--chart-5))",
    },
    neutral: {
        label: "Neutral",
        color: "hsl(var(--muted-foreground) / 0.5)",
    }
  }

function SignalsTable() {
    const { isBotActive } = useBotContext();
    const signals: any[] = [];
    return (
        <Card className={cn(isBotActive && "animated-grid")}>
            {isBotActive && <div className="scanner-line"></div>}
            <CardHeader className="relative z-10 flex flex-row items-center gap-2">
                <BrainCircuit className="h-5 w-5 text-primary" />
                <div>
                    <CardTitle className="font-headline text-primary">Data Analyzer</CardTitle>
                    <CardDescription>
                        Live signals generated by the Analyzer bot.
                    </CardDescription>
                </div>
            </CardHeader>
            <CardContent className="relative z-10">
            <Table>
                <TableHeader>
                <TableRow>
                    <TableHead>Symbol</TableHead>
                    <TableHead>Timeframe</TableHead>
                    <TableHead>Confidence</TableHead>
                    <TableHead>Generated</TableHead>
                </TableRow>
                </TableHeader>
                <TableBody>
                    {signals.length === 0 ? (
                        <TableRow>
                            <TableCell colSpan={4} className="text-center text-muted-foreground">
                                No signals yet. Waiting for data.
                            </TableCell>
                        </TableRow>
                    ) : signals.map(signal => (
                        <TableRow key={signal.symbol}>
                            <TableCell className="font-medium">{signal.symbol}</TableCell>
                            <TableCell>{signal.timeframe}</TableCell>
                            <TableCell>
                                <Badge variant={signal.confidence > 0.8 ? "default" : "secondary"} className={cn(isBotActive && "pulse-glow")}>
                                    {(signal.confidence * 100).toFixed(0)}%
                                </Badge>
                            </TableCell>
                            <TableCell>{signal.createdAt}</TableCell>
                        </TableRow>
                    ))}
                </TableBody>
            </Table>
            </CardContent>
        </Card>
    );
}

function MarketNewsFeed() {
    const { isBotActive } = useBotContext();
    const newsItems: any[] = [];
    return (
        <Card className={cn(isBotActive && "animated-grid")}>
            {isBotActive && <div className="scanner-line" style={{animationDuration: '8s'}}></div>}
             <CardHeader className="relative z-10 flex flex-row items-center gap-2">
                <Rss className="h-5 w-5 text-primary" />
                <div>
                    <CardTitle className="font-headline text-primary">Live Market News</CardTitle>
                    <CardDescription>Breaking news being analyzed for sentiment.</CardDescription>
                </div>
            </CardHeader>
            <CardContent className="relative z-10">
                <ul className="space-y-4">
                     {newsItems.length === 0 ? (
                        <li className="text-center text-muted-foreground py-4">No news items.</li>
                    ) : newsItems.map((item) => (
                        <li key={item.title} className={cn(
                            "flex items-start justify-between gap-4 p-2 rounded-lg",
                            isBotActive && "pulse-glow"
                        )}>
                            <div>
                                <p className="font-medium">{item.title}</p>
                                <p className="text-xs text-muted-foreground">{item.source} - {item.time}</p>
                            </div>
                            <Badge variant={item.sentiment === 'Bullish' ? 'default' : item.sentiment === 'Bearish' ? 'destructive' : 'secondary'}
                                className={item.sentiment === 'Bullish' ? 'bg-green-500/20 text-green-500 border-green-500/30' : item.sentiment === 'Bearish' ? 'bg-red-500/20 text-red-500 border-red-500/30' : ''}
                            >
                                {item.sentiment}
                            </Badge>
                        </li>
                    ))}
                </ul>
            </CardContent>
        </Card>
    )
}

function NewsSentimentChart() {
    const { isBotActive } = useBotContext();
    const sentimentData: any[] = [];
    return (
        <Card className={cn("lg:col-span-2", isBotActive && "animated-grid")}>
            {isBotActive && <div className="scanner-line" style={{animationDuration: '12s'}}></div>}
            <CardHeader className="relative z-10 flex flex-row items-center gap-2">
                <BarChartIcon className="h-5 w-5 text-primary" />
                <div>
                    <CardTitle className="font-headline text-primary">7-Day News Sentiment</CardTitle>
                    <CardDescription>Aggregate news sentiment analysis over the past week.</CardDescription>
                </div>
            </CardHeader>
            <CardContent className="relative z-10">
                <ChartContainer config={chartConfig} className="h-[250px] w-full">
                    <BarChart accessibilityLayer data={sentimentData} margin={{ top: 20, right: 20, bottom: 20, left: 20 }}>
                         <CartesianGrid vertical={false} />
                        <XAxis
                            dataKey="day"
                            tickLine={false}
                            axisLine={false}
                            tickMargin={8}
                        />
                        <YAxis tickLine={false} axisLine={false} tickMargin={8} />
                         <ChartTooltip
                            cursor={false}
                            content={<ChartTooltipContent indicator="dot" />}
                        />
                        <Bar dataKey="bullish" fill="var(--color-bullish)" radius={4} />
                        <Bar dataKey="bearish" fill="var(--color-bearish)" radius={4} />
                        <Bar dataKey="neutral" fill="var(--color-neutral)" radius={4} />
                    </BarChart>
                </ChartContainer>
                 {sentimentData.length === 0 && <p className="text-center text-muted-foreground py-8">Not enough data for chart.</p>}
            </CardContent>
        </Card>
    )
}

export default function SignalsContent() {
  return (
    <div className="grid gap-6 lg:grid-cols-2 lg:items-start">
        <SignalsTable />
        <MarketNewsFeed />
        <NewsSentimentChart />
    </div>
  );
}
